# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 15076  
eureka:
  instance:
    hostname: eureka.vtools.xyz
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    
 
# united-states, france, and vietnam illustrate running 3 intercommunicating instances.  
# This example has them running side-by-side on localhost
# -- which is unrealistic in production
# -- but does illustrate how multiple instances collaborate.
#
# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=united-states SpringCloudServiceRegistrationEurekaServer.jar
# java -jar -Dspring.profiles.active=france SpringCloudServiceRegistrationEurekaServer.jar
# java -jar -Dspring.profiles.active=vietnam SpringCloudServiceRegistrationEurekaServer.jar
 
---
spring:
  profiles: eureka1
  application:
    name: eureka-server-clustered   # ==> This is Service-Id
server:
  port: 15077  
eureka:
  instance:
    hostname: eureka1.vtools.xyz   
  client:
    registerWithEureka: true
    fetchRegistry: true       
    serviceUrl:
      defaultZone: http://eureka2.vtools.xyz:15078/eureka/,http://eureka3.vtools.xyz:15079/eureka/
 
---
spring:
  profiles: eureka2
  application:
    name: eureka-server-clustered   # ==> This is Service-Id   
server:
  port: 15078
eureka:
  instance:
    hostname: eureka2.vtools.xyz      
  client:
    registerWithEureka: true
    fetchRegistry: true       
    serviceUrl:
      defaultZone: http://eureka1.vtools.xyz:15077/eureka/,http://eureka3.vtools.xyz:15079/eureka/
 
---
spring:
  profiles: eureka3
  application:
    name: eureka-server-clustered    # ==> This is Service-Id  
server:
  port: 15079
eureka:
  instance:
    hostname: eureka3.vtools.xyz
  client:
    registerWithEureka: true
    fetchRegistry: true   
    serviceUrl:
      defaultZone: http://eureka1.vtools.xyz:15077/eureka/,http://eureka2.vtools.xyz:15078/eureka/  